import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar";
import { Pixelify_Sans } from "next/font/google"

export const metadata: Metadata = {
  title: "SM-2 Algorithm",
  description: "Generated by create next app",
};

const pixelifySans = Pixelify_Sans({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-pixelify',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pixelifySans.variable} bg-[#ffdeb9] h-screen overflow-y-hidden`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
