import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Navbar";
import { Pixelify_Sans } from "next/font/google"
import { NextAuthProvider } from './providers'
import { getServerSession } from "next-auth";
import Head from "next/head";

export const metadata: Metadata = {
  title: "SM-2 Algorithm",
  description: "Generated by create next app",
};

const pixelifySans = Pixelify_Sans({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-pixelify',
})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/98.css"></link>
      </head>
      <NextAuthProvider>
        <body
          className={`${pixelifySans.variable}`}
        >
          <Navbar session={session} />
          {children}
        </body>
      </NextAuthProvider>
    </html>
  );
}
